// This is a list of flavor combinations that I have made over time as a barista 

var combos = [
  ["Dark Chocolate", "Toasted Marshmallow", "White Chocolate"],
  ["Creme de Menthe", "Dark Chocolate"],
  ["Caramel", "Dark Chocolate", "Hazelnut"],
  ["Dark Chocolate", "Strawberry", "Vanilla"],
  ["Caramel", "Dark Chocolate", "Shortbread"],
  ["Dark Chocolate", "Hazelnut"],
  ["Dark Chocolate", "White Chocolate"],
  ["Caramel", "Dark Chocolate", "Peanut"],
  ["Shortbread", "White Chocolate"],
  ["Brown Sugar Cinnamon", "White Chocolate"],
  ["Caramel", "Brown Sugar Cinnamon"],
  ["Dark Chocolate", "Pepperment"],
  ["Peppermint", "White Chocolate"],
  ["Chocolate Macadamia Nut",
    "Shortbread",
    "White Chocolate"],
  ["Caramel", "Vanilla", "White Chocolate"],
  ["Hazelnut", "Vanilla"],
  ["Shortbread", "Strawberry"],
  ["Almond", "White Chocolate"],
  ["Banana", "Dark Chocolate"],
  ["Brown Sugar Cinnamon",
    "Butter Rum",
    "Caramel",
    "White Chocolate"],
  ["Pumpkin Pie", "White Chocolate"],
  ["Caramel", "Vanilla"],
  ["Peanut", "Vanilla"],
  ["Pumpkin Pie", "Shortbread"],
  ["Brown Sugar Cinnamon", "Shortbread"],
  ["Banana", "Brown Sugar Cinnamon", "Caramel"],
  ["Banana", "Shortbread"],
  ["Strawberry", "White Chocolate"],
  ["Raspberry", "Vanilla"],
  ["Dark Chcolate", "Strawberry"],
  ["Dark Chcolate", "Raspberry"],
  ["Banana", "Peanut"],
  ["Caramel", "English Toffee", "White Chocolate"],
  ["Almond", "Coconut", "Dark Chocolate"],
  ["Honey", "Lavender"],
  ["Dark Chocolate", "Orange"],
];
export default combos; 


